# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3b3a9844067d6f0680a1c0c790328697bb11f8559d40b11e06b2cf91b0e04e4043f22d75d53b318478ad7d1bb2b9a54a4927bf9600098f6a5bdfedfc4e5aef

test:
  secret_key_base: 819af84f96303c60962b91e65aeb919e3f5a69a2a2fde1009af73062adb73c722a7b248603fd4c4e3782b44639ce8465341720acfae5042be878c717641efcba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
